# @package _global_
# Oxford flowers dataset If it's not present, then it will be downloaded & set up
data: "~/datasets/Oxford_Flowers102/images"
image_size: 128
no_wandb: false
load_checkpoint: ~
run_name: ~

codec:
  choice: sd
  checkpoint: "SD"

