# @package _global_
flow: 
    # unet parameters
    epochs: 10000
    num_layers: 8
    num_blocks: 4
    num_heads: 8
    num_channels: 256
    num_residuals: 2
    n_classes: 102
    condition: true

project_name: "flocoder-flow"

