# @package _global_
defaults:
  - base
  - vqgan
  - flow
  - preencoding
  - _self_

# Dataset-specific config - if not present this gets downloaded
data: "~/datasets/Oxford_Flowers102/images"

# Override specific settings
codec:
  choice: vqgan
  project_name: "fc-vqgan-flowers"
  vqgan_checkpoint: "vqgan_best.pt"

flow:
  vqgan_checkpoint: "vqgan_best.pt"
  project_name: "fc-flow-flowers"
